EnableSequence [
	# 扬声器相关路由
	cset "name='codec_out0 Gain 0 Volume' 72%"
	cset "name='IF2 ADC Mux' DAC_REF"
	cset "name='IF3 ADC Mux' IF_ADC1"

	# 扬声器相关路由，这部分应该自动启用
	# cset "name='DAC1 MIXL DAC1 Switch' on"
	# cset "name='DAC1 MIXR DAC1 Switch' on"

	# 扬声器音量50%
	# cset "name='DAC1 Playback Volume' 50%"
	# 设置右扬声器使用右声道
	cset "name='Amp Input1' Right"
]
