SectionDevice."HeadsetMic" {
    Comment "Headset Microphone"

    ConflictingDevice [
        "Speaker"
        "IntMic"
    ]

    EnableSequence [
        # 开启 Headset Mic
        cset "name='Headset Mic Switch' on"

        # 设置 IN1P/IN1N 到录音混音器
        cset "name='RECMIX1L INL' on"
        cset "name='RECMIX1R INR' on"

        # 设置录音混音器输出到 ADC
        cset "name='Stereo1 ADC MIXL ADC1' on"
        cset "name='Stereo1 ADC MIXR ADC1' on"

        # 设置 ADC 音量
        cset "name='IN Capture Volume' 80%"
        cset "name='STO1 ADC Capture Volume' 80%"
    ]

    DisableSequence [
        cset "name='Headset Mic Switch' off"
        cset "name='RECMIX1L INL' off"
        cset "name='RECMIX1R INR' off"
    ]

    Value {
        CaptureMixerElem "Headset Mic"
        CaptureVolume "IN Capture Volume"
        CaptureSwitch "Headset Mic Switch"
    }
}
