SectionDevice."Headphones" {
    Comment "Headphones"

    ConflictingDevice [
        "Speaker"
        "IntMic"
    ]

    Value {
        # PlaybackMixerElem "DAC1"
        PlaybackPCM "hw:${CardId}"
    }

    EnableSequence [
        # cset "name='DAC1 Playback Switch' on"
    ]
    DisableSequence [
        # cset "name='DAC1 Playback Switch' off"
    ]
}
