# Adapted from rt5672 UCM configuration
Define.Speaker "yes"
Define.Headphones "yes"
Define.IntMic "yes"
Define.HeadsetMic "yes"

SectionVerb {
	Include.e.File "EnableSeq.conf"

	If.Controls {
		Condition {
			Type ControlExists
			Control "name='media0_in Gain 0 Switch'"
		}
		Before.EnableSequence "0"
		True {
			Include.pe.File "/platforms/bytcr/PlatformEnableSeq.conf"
			Include.pd.File "/platforms/bytcr/PlatformDisableSeq.conf"
		}
	}
}

# 包含各个设备配置
If.spk {
	Condition {
		Type String
		Empty "${var:Speaker}"
	}
	False.Include.spk.File "Speaker.conf"
}

If.hp {
	Condition {
		Type String
		Empty "${var:Headphones}"
	}
	False.Include.hp.File "HeadPhones.conf"
}

If.intmic {
	Condition {
		Type String
		Empty "${var:IntMic}"
	}
	False.Include.intmic.File "IntMic.conf"
}

If.hsmic {
	Condition {
		Type String
		Empty "${var:HeadsetMic}"
	}
	False.Include.hsmic.File "HeadsetMic.conf"
}
